# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rugex}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lucas Caton"]
  s.date = %q{2011-01-30}
  s.default_executable = %q{rugex}
  s.description = %q{A CLI to test regular expressions on Ruby}
  s.email = %q{lucascaton@gmail.com}
  s.executables = ["rugex"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rugex",
    "lib/rugex.rb",
    "lib/rugex/print.rb",
    "lib/rugex/regex.rb",
    "lib/rugex/string.rb",
    "rugex.gemspec",
    "spec/lib/regex_spec.rb",
    "spec/lib/string_spec.rb",
    "spec/rugex_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/lucascaton/rugex}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{A simple tool for testing regular expressions from Ruby using the terminal}
  s.test_files = [
    "spec/lib/regex_spec.rb",
    "spec/lib/string_spec.rb",
    "spec/rugex_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0.14.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.9"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<thor>, [">= 0.14.6"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.9"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0.14.6"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.9"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

